language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - echo "extension = fileinfo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = gd.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = phar.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = openssl.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install --dev

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  
notifications:
    recipients:
        - hello@cedric.ws
    irc: "chat.freenode.net#kerberos.io"
    email:
        on_success: always
        on_failure: always
